TRUNCATE TABLE EXCHANGE.XXFWGXPT_USER_BEHAVIOR_LOG;
DECLARE
  V_RANDOM_TIMESTAMP NUMBER;
  V_SQLSTMT VARCHAR2(3000);
  V_MT_ID VARCHAR2(100);
  V_MT_TITLE VARCHAR2(100);

BEGIN
  /*SELECT SYSDATE + NUMB/24 FROM (
    SELECT TRUNC(DBMS_RANDOM.VALUE (1, 24)) AS NUMB FROM DUAL
  )*/
  SELECT TRUNC(DBMS_RANDOM.VALUE (1, 24)) AS NUMB INTO V_RANDOM_TIMESTAMP FROM DUAL;
  
  --DBMS_OUTPUT.PUT_LINE('随机数:用户数量:'||V_RANDOM_USER_NUMBER);
  
  --SELECT * FROM EXCHANGE.METADATAS SAMPLE(10) WHERE ROWNUM=1;
  
  FOR REC_LOG IN (SELECT * FROM EXCHANGE.SYSTEM_RUNLOG)
  LOOP
    BEGIN
      SELECT iiid,title into V_MT_ID,V_MT_TITLE FROM EXCHANGE.METADATAS SAMPLE(10) WHERE ROWNUM=1;
      
      INSERT INTO EXCHANGE.XXFWGXPT_USER_BEHAVIOR_LOG
      VALUES(
      REC_LOG.LOG_ID,
      REC_LOG.YHM,
      REC_LOG.YHXM,
      REC_LOG.DKYM,
      TO_CHAR( TO_DATE(REC_LOG.CZSJ, 'yyyy-mm-dd hh24:mi:ss') + V_RANDOM_TIMESTAMP/24 , 'yyyy-mm-dd hh24:mi:ss'),
      TO_CHAR( TO_DATE(REC_LOG.CZSJ, 'yyyy-mm-dd hh24:mi:ss') , 'yyyy-mm-dd hh24:mi:ss'),
      REC_LOG.YHDW,
      NULL,
      REC_LOG.YHGW,
      NULL,
      REC_LOG.YHZDW,
      NULL,
      V_MT_ID,
      V_MT_TITLE,
      REC_LOG.XTFL,
      REC_LOG.CZLX,
      NULL,
      NULL,
      'XXMH',
      REC_LOG.XTMC
      );
    END;
  END LOOP;
  COMMIT;
END;


CREATE OR REPLACE VIEW EXCHANGE.V_USER_BEHAVIOR_LOG_TOES AS
SELECT
T1.*, T2.*
FROM EXCHANGE.XXFWGXPT_USER_BEHAVIOR_LOG T1
LEFT JOIN EXCHANGE.METADATAS T2 ON T1.XXBTBM=T2.IIID
